vim.keymap.set("n", "gcn", ":GitConflictNextConflict<CR>zz")
vim.keymap.set("n", "gcp", ":GitConflictPrevConflict<CR>zz")
vim.keymap.set("n", "gcr", ":GitConflictRefresh<CR>")
vim.keymap.set("n", "gco", ":GitConflictChooseOurs<CR>")
vim.keymap.set("n", "gct", ":GitConflictChooseTheirs<CR>")
vim.keymap.set("n", "gcb", ":GitConflictChooseBoth<CR>")
